### ISSUE TITLE
实测是无效的方案

### ISSUE THREAD

**Issue by sky-nie** [Attect/StaticViewModelStore#1]
楼主测试的例子是两个Fragment:要知道在同一个Activity下的Fragment，完全是可以将viewmdol的生命周期依赖于Activity的，所以，就算不进行任何改造，也以轻松实现同一个Activity下的Fragment之间的数据共享的。现在的难点是多个Activity之间如何共享数据，要知道viewmdol是依赖Activity/Fragment的生命周期而存在的，Destory了就没了。所以，改造后的viewmdol的绝对不能依赖Activity/Fragment创建(可惜viewmdol创建的接口就是只能依赖Activity/Fragment)，凡是依赖窗口创建的，最后必然还是会被销毁，如何做到共享？

**Comment by Attect** [comment]
改造后，不由Activity/Fragment提供ViewModel，不会随着Activity的finish而一定销毁，最终是根据ViewModelProvider被持有的计数决定，但一旦没有任何对象持有ViewModel，仍会销毁。符合设计效果。
演示中，是多个Activity和多个Fragment，不是一个Activity+多个Fragment。
比较符合且常见的场景是App中包含一个常驻前台服务，但这个服务也在必要时会停止，使用这个可以在正确的时机释放相关对象。
